<?php

namespace App\Mcp\Tools;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Tool;

#[Description('Create a new product')]
class CreateProduct extends Tool
{
    /**
     * Handle the tool request.
     */
    public function handle(Request $request): Response
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'sku' => 'required|string|max:255|unique:products,sku',
            'description' => 'nullable|string',
            'unit_price' => 'required|numeric|min:0',
            'stock_quantity' => 'required|integer|min:0',
            'is_active' => 'boolean',
        ]);

        return Response::text('The content generated by the tool.');
    }

    /**
     * Get the tool's input schema.
     *
     * @return array<string, JsonSchema>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()
                ->description('Name of the product.')
                ->required(),

            'sku' => $schema->string()
                ->description('Unique stock keeping unit identifier.')
                ->required(),

            'description' => $schema->string()
                ->description('Optional product description.')
                ->nullable(),

            'unit_price' => $schema->number()
                ->description('Unit price of the product.')
                ->required(),

            'stock_quantity' => $schema->integer()
                ->description('Available stock quantity.')
                ->required(),

            'is_active' => $schema->boolean()
                ->description('Whether the product is active.')
                ->default(true),
        ];
    }

    public function outputSchema(JsonSchema $schema): array
    {
        return [
            'id' => $schema->integer()
                ->description('Unique identifier of the product.')
                ->required(),

            'name' => $schema->string()
                ->description('Name of the product.')
                ->required(),

            'sku' => $schema->string()
                ->description('Stock keeping unit identifier.')
                ->required(),

            'description' => $schema->string()
                ->description('Product description.')
                ->nullable(),

            'unit_price' => $schema->number()
                ->description('Unit price of the product.')
                ->required(),

            'stock_quantity' => $schema->integer()
                ->description('Available stock quantity.')
                ->required(),

            'is_active' => $schema->boolean()
                ->description('Whether the product is active.')
                ->required(),

            'created_at' => $schema->string()
                ->format('date-time')
                ->description('Timestamp when the product was created.')
                ->required(),

            'updated_at' => $schema->string()
                ->format('date-time')
                ->description('Timestamp when the product was last updated.')
                ->required(),
        ];
    }
}
